export const eventName = {
  ERROR: "error",
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  READY_TO_JOIN: "ready-to-join",
  JOIN: "joined",
  COLOR_SELECTED: "color-selected",
  SEND_MESSAGE: "send-message",
  RECEIVE_MESSAGE: "receive-message",
  YOU_JOINED: "you-joined",
  NEW_USER_JOINED: "new-user-joined",
  GAME_START: "game-start",
  READY: "ready",
  FIRST_DRAW: "first-draw",
  GUESS: "guess",
  RESULT_GUESS: "result-guess",
  NEXT_TURN: "next-turn",
};
