export const eventName = {
  ERROR: "error",
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  READY_TO_JOIN: "ready-to-join",
  JOIN: "joined",
  SEND_MESSAGE: "send-message",
  RECEIVE_MESSAGE: "receive-message",
  YOU_JOINED: "you-joined",
  NEW_USER_JOINED: "new-user-joined",
  RTC_OFFER: "rtc-offer",
  RTC_DELIVER_OFFER: "rtc-deliver-offer",
  RTC_ANSWER: "rtc-answer",
  RTC_DELIVER_ANSWER: "rtc-deliver-answer",
  RTC_DISCONNECT: "new-disconnect",
  GAME_START: "game-start",
  READY: "ready",
  FIRST_DRAW: "first-draw",
};
