export const eventName = {
  READY_TO_JOIN: "ready-to-join",
  JOIN: "joined",
  COLOR_SELECTED: "color-selected",
  SEND_MESSAGE: "send-message",
  RECEIVE_MESSAGE: "receive-message",
  GAME_START: "game-start",
  READY: "ready",
  ADD_READY: "add-ready",
  FIRST_DRAW: "first-draw",
  DRAW_RESULT: "draw-result",
  GUESS: "guess",
  RESULT_GUESS: "result-guess",
  NEXT_TURN: "next-turn",
  NEXT_GAMEINFO: "next-gameInfo",
  GAMEOVER: "gameover",
  ROOMOUT: "room-out",
  PLACE_JOKER: "place-joker",
  ONGOING: "ongoing",
};
