const mockDataLead = [
  {
    username: "John Smith",
    profileImageUrl: "https://example.com/john_smith.jpg",
    score: 11000,
    ranking: 1,
    change: 2000,
    rank: "Diamond",
  },
  {
    username: "Jane Doe",
    profileImageUrl: "https://example.com/jane_doe.jpg",
    score: 9300,
    ranking: 2,
    change: 200,
    rank: "Gold",
  },
  {
    username: "Bob Johnson",
    profileImageUrl: "https://example.com/bob_johnson.jpg",
    score: 8800,
    ranking: 3,
    change: -500,
    rank: "Gold",
  },
  {
    username: "Jack Wilson",
    profileImageUrl: "https://example.com/jack_wilson.jpg",
    score: 8200,
    ranking: 4,
    change: -200,
    rank: "Platinum",
  },
  {
    username: "Mike Thompson",
    profileImageUrl: "https://example.com/mike_thompson.jpg",
    score: 7500,
    ranking: 5,
    change: -600,
    rank: "Platinum",
  },
  {
    username: "Emily Davis",
    profileImageUrl: "https://example.com/emily_davis.jpg",
    score: 6800,
    ranking: 6,
    change: -100,
    rank: "Silver",
  },
  {
    username: "David Martinez",
    profileImageUrl: "https://example.com/david_martinez.jpg",
    score: 6500,
    ranking: 7,
    change: -300,
    rank: "Bronze",
  },
  {
    username: "Sara Wilson",
    profileImageUrl: "https://example.com/sara_wilson.jpg",
    score: 5900,
    ranking: 8,
    change: -100,
    rank: "Bronze",
  },
  {
    username: "Chris Johnson",
    profileImageUrl: "https://example.com/chris_johnson.jpg",
    score: 5200,
    ranking: 9,
    change: -300,
    rank: "Bronze",
  },
  {
    username: "Jessica Davis",
    profileImageUrl: "https://example.com/jessica_davis.jpg",
    score: 4900,
    ranking: 10,
    change: -300,
    rank: "Bronze",
  },
];

export default mockDataLead;
